### ISSUE TITLE
Cleaner code

### ISSUE THREAD

**Issue by OctaBruzzesi** [gentilijuanmanuel/react-getting-started#1]
https://github.com/gentilijuanmanuel/react-getting-started/blob/c26386adaf992e3df47af683156d88dbb790e921/react-course/exercise-section-3/src/Clock/Clock.js#L35

The `<h3>` and its closing tag should have the same indentation.
And the state could be better formated.

It would look like this:

```
<h1 className="clock">
  {
    this.state.date.toLocaleTimeString(
      navigator.language,
      {
        hour: '2-digit',
        minute:'2-digit'
      }
    )
  }
</h1>
```
And you could get the state date formated in a function:

```
<h1 className="clock">
  {this.getTimeFormated()}
</h1>
```

**Comment by OctaBruzzesi** [comment]
And I recommend ESLint for the code formatting: https://www.npmjs.com/package/eslint-plugin-react

**Comment by gentilijuanmanuel** [comment]
Thank you, @OctaBruzzesi ! It was a nice shot.

I implemented `eslint` in `react-complete-guide` and `exercise-section-3` projects and I'm feeling the power of the plugin 🔥
