### ISSUE TITLE
PureComponent

### ISSUE THREAD

**Issue by OctaBruzzesi** [gentilijuanmanuel/react-getting-started#2]
https://github.com/gentilijuanmanuel/react-getting-started/blob/c26386adaf992e3df47af683156d88dbb790e921/react-course/exercise-section-3/src/Clock/Clock.js#L5

It may be better to use a PureComponent instead of a Component https://reactjs.org/docs/react-api.html#reactpurecomponent

**Comment by gentilijuanmanuel** [comment]
As we told after this issue, functional component would be a better option. Implemented in `exercise-seciton-3` project. In `clock` component, I'll leave it as class component, just to keep both versions.

Closed!
