### ISSUE TITLE
Change className

### ISSUE THREAD

**Issue by OctaBruzzesi** [gentilijuanmanuel/react-getting-started#4]
https://github.com/gentilijuanmanuel/react-getting-started/blob/c26386adaf992e3df47af683156d88dbb790e921/react-course/exercise-section-3/src/UserInput/UserInput.js#L7

It would be better to use something like: 'user-input'.

**Comment by OctaBruzzesi** [comment]
https://medium.freecodecamp.org/css-naming-conventions-that-will-save-you-hours-of-debugging-35cea737d849

**Comment by gentilijuanmanuel** [comment]
Changed. Thanks!
